server:
  port: 8080
  servlet:
    context-path: /yokult
  
spring:
  # DataSource
  datasource:
    url: jdbc:mysql://localhost:3306/yokult?useSSL=false&serverTimezone=GMT%2b8&useLegacyDatetimeCode=false  
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  # SessionFactory
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        
  # mongoclient
  data:
    mongodb:
      uri: mongodb+srv://vicky:tibame888@cluster0.sw4btkx.mongodb.net/?retryWrites=true&w=majority
      database: patient
      
  # jackson
  jackson:
    default-property-inclusion: non-null
    time-zone: GMT+8